<html>
	<head>
	    <?php echo $this->headLink()->appendStylesheet('/CSS/kaisers.css') ?>
		
		<link rel='shortcut icon'href='/test.ico'>
		
		<title>
			Kaisers Restaurant
		</title>
	</head>

	<body>


	<body>
		<div class="header">
			<a href="<?php echo $this->url(array('controller'=>'index','action'=>'index'));?>">
				Kaisers Restaurant
			</a>
		</div>
	
		<div class="linkrow">
 			<a href="<?php echo $this->url(array('controller'=>'index','action'=>'index'));?>">
 				World
 			</a>
 			
 			||
 		
			<a href="<?php echo $this->url(array('controller'=>'index','action'=>'asdf'));?>">
				Mayte
			</a>
		</div>
  
		<div class="mainframe">
			<?php echo $this->layout()->content ?>
		</div>
		
		<div class="footer">
			Kaisers Restaurant - 9800 Spittal
		</div>
	</body>
</html>

